# Generated by Django 3.0.8 on 2023-04-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestPassword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, unique=True)),
                ('token', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
